apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: default
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
      - containerPort: 80
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.5"
